# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: 
    push:
        branches:
        - main

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_PW_CDN_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_PW_CDN_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_PW_CDN_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
          echo "Creating dummy text file..."
          echo "This is a dummy file for Azure Blob Storage upload." > dummy.txt
          echo "Uploading dummy text file to Azure Blob Storage..."
          az storage blob upload -c builds --auth-mode login --account-name anamplaywright -f dummy.txt -n driver/dummy.txt"
